

on: [push]


jobs:
  build_job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: CI
      
  test_job:
    runs-on: ubuntu-latest
    steps:
       - uses: ./ # Uses an action in the root directory
       - name: Test job
         with:
          numero: 'Teste CI'
          
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado!"
      - name: deploy
